### ISSUE TITLE
Relay bot name is not shown on message

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#105]
new-ui:

![2018-08-07_23 18 50](https://user-images.githubusercontent.com/8090459/43785169-5a54f368-9a98-11e8-944f-5c752ec2e282.png)

0.06.4:

![5211f94b8bcfabf16a852907bc76001ee321be](https://user-images.githubusercontent.com/8090459/43785220-6ef2e97e-9a98-11e8-8bfe-53e57e44c5fd.png)

**Comment by VOID001** [comment]
Get it, I will investigate this issue recently
