### ISSUE TITLE
Add reconnect popup menu item for server buffer

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#107]
In server buffer's popup menu, there is an item "Disconnect" for disconnecting from IRC server, but not an "Reconnect" item for reconnecting to server.

**Comment by VOID001** [comment]
@SilverRainZ can I add a event called reconnect to sui_event.h ?

**Comment by SilverRainZ** [comment]
Sounds good :D

**Comment by SilverRainZ** [comment]
咕咕咕 ~~again~~？

**Comment by VOID001** [comment]
No, give me some time, I won't gugugu this time :(

I will provide DDL on each task assigned

**Comment by VOID001** [comment]
The disconnect should work as a callback event function

**Comment by VOID001** [comment]
2c6589f3b126b733269058471e886b870bd4cb72

**Comment by SilverRainZ** [comment]
Resloved via #145.
