### ISSUE TITLE
Drop ignored user list

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#115]
Currently srain implment the ignore function by storing the ignored nickname in `SrnChat->ignore_nick_list`, this implementation makes it difficult for us to know if the user is ignored when we only have the reference to a user.

In addition, I think "ignore" is an attribute of user but not attribute of  chat, so I considering add `SrnChatUser->is_ignored` as replacement of `SrnChat->ignore_nick_list`.

**Comment by ZWindL** [comment]
意识到一个新的问题：如果在 /ignore xxx 的时候，xxx 没有在线，那么如何在抛弃 ignore_list 的情况下实现 ignore 这个当前不在线的用户呢？

**Comment by SilverRainZ** [comment]
@ZWindL 我的想法是即使这个用户不在线，也为他建立一个 user 实例，屏蔽用户的量级不会很大，这样的内存消耗应该是可以接受的。

**Comment by ZWindL** [comment]
@SilverRainZ 等待这个用户上线后如何处理两个 user 实例的冲突？

**Comment by SilverRainZ** [comment]
不会冲突啊，用户上线（传统 IRC 里你只能通过 JOIN 或者用户主动给你发消息感知到），调 `srn_server_add_and_get_user` 的时候，如果用户已经存在了是不会重复创建的，置 `SrnServerUser->is_online` 为 `TRUE` 就行了。

**Comment by ZWindL** [comment]
@SilverRainZ 啊！原来如此！

**Comment by SilverRainZ** [comment]
@ZWindL 看起来改得差不多了，如果 UI 那边不打算改的话，求有空的时候整理一下开个 PR。
