### ISSUE TITLE
When config file missing, srain should create a default one for current user

### ISSUE THREAD

**Issue by VOID001** [SilverRainZ/srain#124]
When config file missing, srain should create a default one for current user and store it in $XDG_CONFIG_HOME/srain/srain.cfg

**Comment by SilverRainZ** [comment]
I think Srain should not actively create a configuration file when it is missing.

**"Create configuration file only when user changes default configuration"** will be better.

**Comment by VOID001** [comment]
Well, time is a bit too long though, I thought this issue is opened because of srain cannot work if it doesn't find a config file. And in that case I think srain shouldn't complain and exit, it may create a default config file for the user in his/her $XDG_CONFIG_HOME, or just use the very basic defafult internal config without creating a default one

**Comment by SilverRainZ** [comment]
Now user dir/file will be automatically created when needed.
