### ISSUE TITLE
No option to run in the background

### ISSUE THREAD

**Issue by 9898287** [SilverRainZ/srain#135]
Version:

`0.06.4-git@0.912.1652368`

From flatpak `im.srain.Srain/x86_64/stable`

I cannot find a way to keep srain running in GNOME. Closing srain removes my saved IRC networks and channels. Is there a config that allows me to keep it running in the background?

**Comment by SilverRainZ** [comment]
Does your gnome have a tray icon area? click the srain tray icon to hide srain.

**Comment by SilverRainZ** [comment]
This weekend I will try use GNOME 3.30 and Polaris to see how they actually  approach this.

**Comment by SilverRainZ** [comment]
As I see, If you set the "Run in background" option, Polaris just hide its window, and there is no any interface on GNOME to let it visible again except run Polaris again? What a great design~

**Comment by SilverRainZ** [comment]
Now srain will no exit when its window is closed (just hide the window), you can start srain again to activate.

If you want to apply this change right away, you can build srain by yourself from the github master.
