### ISSUE TITLE
Adwaita Dark theme (GNOME) makes message labels invisible when window is focused

### ISSUE THREAD

**Issue by 9898287** [SilverRainZ/srain#136]
<b>Environment:</b> GNOME 3.30

<b>Branch:</b> Master (freshly built)

![Demonstration exhibit1](https://i.imgur.com/OYDiPml.png)
![Demonstration exhibit2](https://i.imgur.com/q0Dz8xs.png)

**Comment by SilverRainZ** [comment]
Currently srain does not know whether your theme a dark theme, try add `gtk-application-prefer-dark-theme=1` to you gtk3 settings (`~/.config/gtk-3.0/settings.ini`).

**Comment by SilverRainZ** [comment]
BTW, on GNOME, set `csd = true`in `~/.config/srain/srain.cfg` to enable CSD of srain will be better. 

ref: http://doc.srain.im/en/latest/config.html

**Comment by SilverRainZ** [comment]
Added some code to guess if the current theme is dark XD.
