### ISSUE TITLE
Cannot add custom server anymore

### ISSUE THREAD

**Issue by 9898287** [SilverRainZ/srain#137]
<b>Details:</b>
<ul> 
    <li><b>Version</b>: 1.0.0rc1-git@0.1078.ffd9712 (current master branch)</li>
    <li><b>Platform</b>: GNOME 3.30 on Manjaro (Arch deriv) Linux
</ul>

I can't find a way to log into a custom server. The dropdown menu in "Advanced Mode" found in the "Connect" menu has no option for a custom server.

![demo](https://i.imgur.com/XAK8Nkf.png)

**Comment by SilverRainZ** [comment]
The topest combo box is server name, it can not duplicated with any others predefined or connected server. So please try changing the server name and click connect again?

BTW, the login method is not fully implemented yet, only `none` and `sasl-plain` can be used, see #122.

**Comment by 9898287** [comment]
The top ComboBox (Server) has no option for a custom server? I'm a little bit confused.

![](https://i.imgur.com/giWIRGD.png)

**Comment by SilverRainZ** [comment]
Isn't it editable?

**Comment by 9898287** [comment]
This is editable. Probably was a problem in my libgtk libraries. 
Although the UI needs a bit of a polish, for example adding a `(Custom Server)` in the ComboBox. 

Closing this.
