### ISSUE TITLE
Write documents

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#45]
- [x] Development document
- [x] Command manual
- [ ] Installation guide
- [ ] User manual

**Comment by SilverRainZ** [comment]
- [ ] API document for SUI
- [ ] API document for SIRC

**Comment by SilverRainZ** [comment]
还用 sphinx 好吧！

**Comment by SilverRainZ** [comment]
http://breathe.readthedocs.io/en/latest/

**Comment by SilverRainZ** [comment]
暂时放弃编写开发文档，能写好注释就不错了。

**Comment by ZWindL** [comment]
:(
