### ISSUE TITLE
Picture preview bug

### ISSUE THREAD

**Issue by ZWindL** [SilverRainZ/srain#53]
Multi message from one user contains image url can cause 'load img' button display many times though the image url shows only once.
![842a](https://cloud.githubusercontent.com/assets/5116996/21072307/a476244e-bef8-11e6-9122-e494b34a15c6.jpeg)

**Comment by SilverRainZ** [comment]
fixed.

![](http://img.tjm.moe/ba/4608da754d0e2ad30a40605e8e3419e71ca381.png)

**Comment by SilverRainZ** [comment]
Now srian can preview multiple image the one message.

![](http://img.vim-cn.com/66/4431b095c306c185a9c8b57e886af85dd51ae8.png)
