### ISSUE TITLE
Compatibility with Windows

### ISSUE THREAD

**Issue by ZWindL** [SilverRainZ/srain#57]
Idea from InusualZ@#srain

**Comment by SilverRainZ** [comment]
I am trying use pure glib&gtk function in the code, compatibility with Windows is possible, but no
high priority task.

**Comment by BruceZhang1993** [comment]
disagree. gtk on windows looks like a @ZWindL

**Comment by SilverRainZ** [comment]
@BruceZhang1993 on windows you can use https://github.com/BruceZhang1993/imotion-client :-)

**Comment by SilverRainZ** [comment]
近期找时间尝试适配。

**Comment by smaragdus** [comment]
@SilverRainZ 
I will be glad if you manage to port [srain](https://srain.im/) to Windows- there are not so many good and free IRC clients for Windows in active development.

**Comment by SilverRainZ** [comment]
@smaragdus I will, Srain will have window support at version 1.0. Currently I am working on stuff about config panel. If everything goes well, the version 1.0 will release before june.

Thanks for you support.

**Comment by smaragdus** [comment]
@SilverRainZ 

This is a great piece of news. If needed I can test the Windows build before the official release.

I have one request about the Windows build- portable version or portable mode- an option to save data and settings in program folder (where is the executable)- thus the users would be able to have Srain on external drives and use it on other machines with all its data and settings. As far as I know portable software is usually called "green" software in Chinese. There are different ways portable mode can be implemented, for example:

- separate portable version- extract the archive and run the executable;
- portable installation option;
- command-line argument- if Srain is started with 'srain.exe -portable' parameter it saves data and settings in program folder;
- portable flag- on program start Srain checks program folder for 'portable' flag and if it exists Srain saves data and settings to program folder;
- a special sub-folder, for example 'Data' or 'Settings' in program folder triggers portable mode;

I know it is too early to talk about this but I will be glad of the Windows build of Srain can be run in portable mode from the very first release.

Best wishes and good luck!

**Comment by SilverRainZ** [comment]
Just successfully built on windows:

![srain-on-windows](https://user-images.githubusercontent.com/8090459/40589108-55815d2e-621a-11e8-9d6f-fa2a05b6104b.png)

**Comment by smaragdus** [comment]
@SilverRainZ 
Great news! Will the Windows version have all the features the Linux version has?

**Comment by SilverRainZ** [comment]
@smaragdus Excluding exceptions(e.g. some libraries not available on Windows), Windows version will have the same functions as other platforms.

**Comment by SilverRainZ** [comment]
Work of Windows porting is on branch `mingw`.

**Comment by SilverRainZ** [comment]
See #111 for the progress of Windows port.

**Comment by SilverRainZ** [comment]
![virtualbox_win10_16_08_2018_10_56_20](https://user-images.githubusercontent.com/8090459/44184799-48bc9780-a143-11e8-84f1-6eae6a5a8570.png)

**Comment by SilverRainZ** [comment]
@smaragdus @InusualZ

I wrote some documents about how to install latest Srain on Windows: https://github.com/SilverRainZ/srain/blob/e6419d7deaf30ef2cbc9e8e795e07b8ecf66afad/doc/install.rst#windows , can you have a try?

**Comment by SilverRainZ** [comment]
Sorry, the aboved link seems not up to date, I will update it tomorrow.

**Comment by SilverRainZ** [comment]
The corrected one: https://github.com/SilverRainZ/srain/blob/4837d66c6bdd5052f90158b85a032092c71ea31d/doc/install.rst#windows

**Comment by BruceZhang1993** [comment]
![screenshot_20180920_113219](https://user-images.githubusercontent.com/6873988/45794745-b459cd80-bcca-11e8-99ac-e52a00dac213.png)

Building error report

makepkg build failed if my Windows username contains 1+ spaces. Eg, microsoft account login.

**Comment by SilverRainZ** [comment]
@BruceZhang1993 Cause by #131, will be fixed ASAP.

**Comment by SilverRainZ** [comment]
This issue will be closed in 1 week.
