### ISSUE TITLE
Documentation review for 0.06

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#63]
Srain 0.06 will comes with a serial of help documentations. Most of them are completed.
I am not native English speaker and not very well in English, so I hope there are someone can help me to review Srain's documentations.

If you want to help srain, please comment on this issue, then visit the following links and read it carefully.

If you find any mistakes or something ambiguous, please report them to here, if you finished reading of  some of documentation, tell me, too.

Thank you!

I hope that the following documentations can be reviewed by at least 2 people. :-)

- [x] Quick Start [1/4] http://doc.srain.im/en/latest/start.html
- [x] FAQ [1/4] http://doc.srain.im/en/latest/faq.html
- [x] Installation [2/4] http://doc.srain.im/en/latest/installation.html
- [x] Preference Manual [3/4] http://doc.srain.im/en/latest/prefs.html
- [x] Commands Manual [1/4]  http://doc.srain.im/en/latest/commands.html
- [x]  Miscellaneous [2/4] http://doc.srain.im/en/latest/misc.html

---

Updated: 2017.7.29 all help documentations are completed.

**Comment by rtlanceroad** [comment]
In the **Priority and Fallback** section, **Preference Manual** chapter, the following paragraph has some typoz:
```
Another similar group is chat, chat contains configuration of chat panel, such as whether show topic, whether save chat log and etc. Every server group can contains a chat group and a chat_list list. Elements in chat_list are also identified with unique name.
```
Those are users' actions, so it will be good to see:
```
such as whether *to* show topic, whether *to* save chat log and etc. Every server group can *contain* a chat group and a chat_list list. Elements in chat_list are also identified with unique *names*.
```
check out the boded.

**Comment by rtlanceroad** [comment]
```
As mentioned above, The priority of user configuration always higher than system’s, so we can get the priority sorting of server and chat group:
```
There should be a verb there:
```
As mentioned above, The priority of user configuration **is** always higher than system’s, so we can get the priority sorting of server and chat group:
```

**Comment by rtlanceroad** [comment]
In the **Syntax section**, **Commands Manual** chapter, there is one paragraph: 
```
option oftenly used as the switch of a flag or a way to chagne some default value. For an example, in command /connect -tls -port 6697, option -tls is just a flag that tell srain use secure connections with TLS. And -port requires a value, if -port is not specified, program will use the default value of it. Refer /connect for more details.
```
often is an adverb, no oftenly such thing. 

```
option **is often** used as the switch of a flag or a way to **change** some default **values**. **For example**, **The** command /connect -tls -port 6697, option -tls is just a flag that **tells** srain **to** use secure connections with TLS. And -port requires a value, if -port is not specified, program will use the default value **6667**. **Check** /connect for more details.
```

**Comment by rtlanceroad** [comment]
```
If a vaule starts with a hyphen - or contains whitespaces, it should be enclosed by singly quotation mark '.
```
singly is an adverb, we need an adjective before none here. Therefore, we replace it with `a single` .

**Comment by rtlanceroad** [comment]
```
An argument is similar to vaule, but **commonly** it doesn’t have a default value so it can not be **omitted** (actually it depends on the **implemention** of the command). If the first argument starts with a hyphen -, it should be enclosed by **a single** quotation mark '. If an argument contains whitespaces, it should be quoted too. Specially, the last argument can **contain** whitespace without quoted.
```
```
If you want to use a **a single** quotation mark in a quoted text, use backslash \ to escape it. For backslash itself, use double backslash \\.
```

**Comment by SilverRainZ** [comment]
@rtlanceroad Thank you! fixed.

**Comment by SilverRainZ** [comment]
@rtlanceroad Quick start, FAQ and miscellaneous are completed now, can you please review it in free time?

**Comment by rtlanceroad** [comment]
Of course.

**Comment by rtlanceroad** [comment]
In the **Hot Keys** section, Miscellaneous chapter, 
```
**Customized** hot **keys** will be supported in the future.
```
In the **Frequently Asked Questions** chapter,
```

**Does** Srain support Windows?( Also correct outlines )

**Not yet**, Windows support is in **the** plan.

```
Why does the **image upload** button not **work**? (  Also correct outlines  )
This function is implemented by a python plugin, **therefore**you should install python3-urllib3 and python3-request to let it **work**.
```
```
Why can’t I see people’s avatar?

There is not a specification for user avatar in IRC protocol (IRCv3 has an idea about it), so currently the avatar function is simply implemented by a python plugin, **therefore**you should install python3-urllib3 and python3-request to let it **work**.
**Besides**, you should set show_avatar to true in your configuration.
```
```
What is “relay message transform”?

There are many relay bots forward messages from other **IMs** to IRC network, “Relay message transform” **makes** these messages easier to read.
```

**Comment by rtlanceroad** [comment]
In the **Connect Using Command** section, **Quick Start** chapter,
```
**Enter** the following commands in input entry: (Remove duplicate word `enter`)
```

**Comment by rtlanceroad** [comment]
In the Usage section, Commands Manual chapter,
/server part: 
```
Create a server and **connect to** it immediately. It will become the default server **automatically**. (Remove duplicate `connect to`)
```

/connect
```
The following commands should run under the context which has a “default server”, Briefly, these **commands** must **be** executed after /server connect or /connect command.
```

/relay & /unrelay
```
This command is unstable, it may be **implemented** as a plugin in the future.
```

/query & /unquery
```
For /unquery , If **no nick is** specified, **it stops** the current private chat.
```

/part
```
Leave specified channel(s) with optional reason, channels are separated by commas ,. If **no channel is** specified, **it leaves** the current channel.
```

/topic
```
Set the current channel’s topic. If **no topic is** specified, **it** just **displays** the current channel’s topic.
```

/me
```
Send **an** action message to the current target.
```

/invite
```
Invite somebody to join a channel. If **no channel is** specified, **it falls back** to current channel.
```

/kick
```
Kick somebody from a channel, with optional reason. If **no channel is** specified, **it falls back** to current channel.
```

**Comment by rtlanceroad** [comment]
Done! at least from grammar :)

**Comment by ZWindL** [comment]
I've read [Preference Manual](http://doc.srain.im/en/latest/prefs.html) and [installation](http://doc.srain.im/en/latest/installation.html) and they are all easy to understand, typos are fixed by @rtlanceroad, thanks a lot.

**Comment by SilverRainZ** [comment]
All fixed~
