### ISSUE TITLE
ctcp command support

### ISSUE THREAD

**Issue by ZWindL** [SilverRainZ/srain#65]
We need a ctcp command to query other user's client information and send/reply other users ctcp query.

- [x] ACTION must
- [x] CLIENTINFO should
- [x] FINTER may
- [ ] DCC may
- [x] PING must
- [x] SOURCE may
- [x] TIME should
- [x] VERSION must
- [x] USERINFO may

**Comment by SilverRainZ** [comment]
FYI: https://modern.ircdocs.horse/ctcp.html
