### ISSUE TITLE
求添加SASL功能qwq

### ISSUE THREAD

**Issue by OriginCode** [SilverRainZ/srain#68]
RT，這樣會更方便一點吧

**Comment by SilverRainZ** [comment]
在计划中。

**Comment by SilverRainZ** [comment]
This feature will come with version 0.06.4.

**Comment by SilverRainZ** [comment]
SASL PLAIN is supported.

**Comment by SilverRainZ** [comment]
SASL PLAIN now can be control by cofiguration or connnection panel on UI.

This feature will be included in version 1.0, close issue for now.

![2018-05-19_19 16 18](https://user-images.githubusercontent.com/8090459/40268050-2af22958-5b99-11e8-98fe-1f08ce5f739d.png)
