### ISSUE TITLE
Remember channel, server support!

### ISSUE THREAD

**Issue by OriginCode** [SilverRainZ/srain#69]
- [x] Remember channel.
- [x] Remember server.

**Comment by ZWindL** [comment]
@OriginCode Actually, you can add it into your config file, just like another clients.
You may need this document [Preferences Manual](https://doc.srain.im/en/latest/prefs.html)

**Comment by SilverRainZ** [comment]
@ZWindL No in config file, but rc file, please refer to: http://doc.srain.im/en/stable/commands.html#context

The support for auto{connect,join} in configuration file will be added in the future. When this work in progress, I will reopen this issue.

**Comment by SilverRainZ** [comment]
Impl in https://github.com/SilverRainZ/srain/commit/fbb413c5928d3e635b1c17c371100b909b2d3d64 .

**Comment by SilverRainZ** [comment]
Configuration items `auto-connect` and `serve.auto-join` is used to do that.
