### ISSUE TITLE
Can not  receive some msg.

### ISSUE THREAD

**Issue by yinflying** [SilverRainZ/srain#72]
srain will lose some the message like:
```
https://github.com/search?q=cc&type=Users&utf8=%E2%9C%93
```
https://img.vim-cn.com/b8/1abbbd56baee1225d9fa35496fa57ea624f179.png
the url have been parsed but can not see.

**Comment by yinflying** [comment]
ok, it have fixed at the new version  0.8

**Comment by SilverRainZ** [comment]
This should be fixed in https://github.com/SilverRainZ/srain/commit/6b9582e48515f97df62dcd9ee5accecb12df0938. Try git version or waiting for 0.06.3.
