### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by SilverRainZ** [SilverRainZ/srain#81]
- [x] Using CSD(Client Side Decoration), idea from /u/realnowhereman@reddit: ![](https://i.imgur.com/FJ5iAKA.png)
- [x] Square application icon, thx to @cousin_luigi
- [x] New default theme
- [x] Darker theme
- [ ] ~~MIRC color map?~~

**Comment by SilverRainZ** [comment]
CSD support and new connection panel:

![2018-05-19_19 10 09](https://user-images.githubusercontent.com/8090459/40268000-48df052c-5b98-11e8-87c6-5d8943de41d3.png)
![2018-05-19_19 09 55](https://user-images.githubusercontent.com/8090459/40267999-487ff1c2-5b98-11e8-9d44-011db7c57079.png)

**Comment by SilverRainZ** [comment]
I am considering make a theme without the "bubble", but it is hard to let the message list to be a list of  "plain text" in theme level: It can looks like plain text, but you can not select multiple messages as a paragraph of text. Is it acceptable?

@cpba @evacchi @ZWindL

**Comment by cpba** [comment]
In general there's nothing wrong with preventing this, as long as the user has another way of doing it.

Would the user have to select the text boxes one by one?

Being able to copy conversations is useful for users who may wish to use external language translation, or even just as an ad-hoc log feature.

**Comment by SilverRainZ** [comment]
> Would the user have to select the text boxes one by one?

@cpba I will do some work to let user can select multiple text boxes via select and drag.

**Comment by SilverRainZ** [comment]
#98 has been merged.

**Comment by Justinzobel** [comment]
What happened to the dark theme? I'd love to enable it.

**Comment by SilverRainZ** [comment]
@Justinzobel Just choose a system wide dark GTK theme, it will be enabled automaticlly.
