### ISSUE TITLE
Icons look blurry on hidpi screens

### ISSUE THREAD

**Issue by cpba** [SilverRainZ/srain#92]
Some icons look blurry when viewed on a hidpi screen.

![blurryicons](https://user-images.githubusercontent.com/11727844/37297365-ca7b26fc-261d-11e8-952d-846c5878fbce.png)

This is most likely because they are 16px raster images being scaled up, the "about" icon looks fine because it's originally a 190px png scaled down.

A possible solution would be to use vector based icons and scale them to all possible sizes using rsvg during build time. Are there svg versions of the current icons available?

If finding the originals is too hard, maybe they could be replaced with other free scalable icons found around the web such as:

- https://feathericons.com/
- https://useiconic.com/open
- https://material.io/icons/ (i'm unsure about the license on these)
- Or gnome's own symbolic icons.

**Comment by SilverRainZ** [comment]
Yes there are original versions for some of this icons: http://doc.srain.im/en/stable/resources.html
In fact I want to paint them by self but the progress is stalled :-(.

**Comment by cpba** [comment]
Oh that's good, I don't see any vector icons in there but they have raster icons up to 512px, we should be able to fix the problem just by adding the extra resolutions, I'll give it a try.

It will be more cumbersome than having a scalable svg and creating them with a script, but it only needs to be done once.

**Comment by cpba** [comment]
48px icons are a pretty neat improvement:

![srain-48px](https://user-images.githubusercontent.com/11727844/37356456-48e02f24-26e6-11e8-81f0-f00907819ef7.png)

 I couldn't find the photo icon with the envelope, is it from another set?

**Comment by SilverRainZ** [comment]
hmm... I forgot that where the envelope icon came from.

**Comment by SilverRainZ** [comment]
PR #94 looks work well, thank you!
